### ISSUE TITLE
Mongo fails with server 500 and no reason as to why

### ISSUE THREAD

**Issue by EmirGluhbegovic** [ethanresnick/json-api#136] opened 2017-11-06 08:01 UTC
Hey there,

I was having a problem where I received a 500 server error but given no clue as to why. I went digging into the node modules folder for jsonAPI and inside the build/API_ERRORS I believe it was called I added a console.log(e) and saw that the error was mongo complaining about dup email_1. 

Have had this issue a few times now, is there a way to make those errors pass back up to the server so I can catch them and pass back a useful message back to the user?

Regards,
Emir

**Comment by ethanresnick** [comment] 2017-11-09 09:58
I understand what you're asking for, and there's no way to do this at present unfortunately. Everything that's not a mongoose validation error is treated as an internal error whose details aren't exposed to the user, and there's no way to customize this at the moment. 

However, I'm working on a refactor in [this branch](https://github.com/ethanresnick/json-api/tree/v3-evolution-over-rewrite) that will support what you're talking about. That refactor improves a lot of the underlying architecture of this library to make it more extensible. The new code already works for many new features (see changelog) and is generally stable, but the feature you're requesting isn't done yet. I hope to finish it this weekend.

**Comment by EmirGluhbegovic** [comment] 2017-11-09 10:04
Hey Ethan, thank you for the feedback and support you giving to the community. Probably not too easy maintaining an open-source repo with people always demanding. Was thinking of doing a pull request. Will look forward to the update.
Thank you again.

**Comment by EmirGluhbegovic** [comment] 2017-11-17 05:08
@ethanresnick Hey, hope things are going well.
Want to ask if there has been any update with regards to the above?

**Comment by ethanresnick** [comment] 2017-11-18 01:20
Hey, thanks for checking in. I've made some good progress, but don't quite have something I can push yet. I'll keep working on it tonight and hopefully I can finish.

**Comment by ethanresnick** [comment] 2017-11-19 10:43
Didn't quite finish. If it's not ready by Monday EOD, I'll push what I have and maybe you can help with it?

**Comment by EmirGluhbegovic** [comment] 2017-11-19 10:56
Sure, just let me know what you need to get done

**Comment by ethanresnick** [comment] 2017-11-22 08:54
@EmirGluhbegovic Are you using the library off of master, or using the v3 beta (published to npm from the `v3-evolution-over-rewrite` branch)? If you're not on the v3 beta, have you launched your API yet? I'm asking because, if you're on the beta (or can easily move to it), that greatly effects what a PR for this issue would look like. My hope is that you are on the beta, because its underlying abstractions are far, far more poweful, and I'd like to address this by improving them further. But, if you're stuck on v2, we can try to figure out what a PR for that might look like as well.

**Comment by ethanresnick** [comment] 2017-11-23 07:41
Ok, this is now supported in v3 alpha 11, just published on NPM! I'll write up some docs soon, esp if you're already on v3.

**Comment by ethanresnick** [comment] 2017-11-23 10:38
Ok, I've put some v3 documentation up:

1. This [commit message](https://github.com/ethanresnick/json-api/commit/c394e2c2cdeae63acf3c6660516891a2cf56affb) describes the new features in v3 pretty thoroughly. You can see that they make a lot of powerful things possible. The `v3-evolution-over-rewrite` branch's README also contains some more details.

2. The [changelog](https://github.com/ethanresnick/json-api/blob/v3-evolution-over-rewrite/UPGRADING.md#300-alpha) details pretty thoroughly the breaking changes. Most of these changes are to internal APIs that you're unlikely to be using, so you probably won't have to do much. The exceptions are around filtering -- the `?filter` query parameter format has changed, so your clients may need to be updated (though you won't need to do anything server-side) -- and around which mongoose validators are run on PATCH requests (which may or may not be an issue; if it is, let me know).

3. I've updated the [example api repo](https://github.com/ethanresnick/json-api-example/tree/v3-wip) to demonstrate how to use some of these new features.

Hopefully that all helps!

**Comment by EmirGluhbegovic** [comment] 2017-11-24 07:31
Hey, I'm busy with doing the update.
I am getting a server error through express: "express deprecated req.host: Use req.hostname"

Just need to update: node_modules/json-api/build/src/http-strategies/Express.js:62:56

**Comment by ethanresnick** [comment] 2017-11-24 08:40
Glad the upgrade is going relatively smoothly.

Re the `req.hostname` error, it's because the ExpressStrategy now takes/needs a new `host` option. See the [example in the README](https://github.com/ethanresnick/json-api/blob/v3-evolution-over-rewrite/README.md#example-api) for how to set that. The rationale, basically, is that the library uses the host value in a few places (I think mostly with url templates), and it's not reliable to read the value out of the `Host` header, so the user must provide it manually.

**Comment by EmirGluhbegovic** [comment] 2017-11-24 09:03
So I set the explicitly set the option: const opts = { host: 'localhost:3114' }?

I keep getting an error when I do: localhost:3114/api/users?filter=(email,test@example.com)

Am I doing something incorrectly? Getting the following message: 
"An unknown error occurred while trying to process this request"

Think I need to log in in build API ERROR to catch it.

**Comment by ethanresnick** [comment] 2017-11-24 09:10
Yes, you should set the host explicitly. With that in place, though, I'm not sure why adding a filter would trigger an error. Try running your server with the DEBUG environment variable set to `json-api:*`. That should hopefully show a more detailed error message.

**Comment by EmirGluhbegovic** [comment] 2017-11-24 09:15
Getting: "API Controller caught error Error: Filter criteria must be a list."
Maybe I need to move this  another issue?

**Comment by ethanresnick** [comment] 2017-11-24 10:08
Yeah, another issue would be good. I'll close this out. In the meantime, I'll see if I can reproduce.

**Closed by ethanresnick** 2017-11-24 10:08 UTC
