### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by paul-barry-cengage** [ethanresnick/json-api#5] opened 2015-03-11 04:20 UTC
I recently discovered this repo after attempting to roll my own. Thank you for your hard work on this, I've learned first hand that it's not as easy as it looks.

As I attempted to use your example, I discovered an undefined variable.

    var registry = new API.ResourceTypeRegistry();
    var controller = new API.controllers.Base(Registry);
    var adapter = new API.adapters.Mongoose(models);

Is 'Registry' defined somewhere? My linter is throwing an error there. 

If I change 'Registry' to 'registry' (as I assume it should be), I then get the following error when pinging the endpoint: 

    {"error":"TypeError: Cannot call method 'adapter' of undefined\n at prototype.GET (/node_modules/json-api/build/lib/controllers/Base.js:24:31)

Again, I totally appreciate your efforts here. Thanks.

**Comment by ethanresnick** [comment] 2015-03-11 21:26
Thanks Paul!

You're right that `Registry` should be `registry`, and I've now updated the readme accordingly. From the error message, I can't tell exactly what the problem is, but I've now fixed a couple other bugs in the example too. Try out the latest version and let me know if it works!

About the repo in general: my hope is to have it all up to date with the latest spec within a week or so. (That work is happening in the rc2 branch.) If you catch any other bugs and wan't to contribute, I'd appreciate it!

**Closed** 2015-04-02 21:11 UTC
