### ISSUE TITLE
Can't save a relationship in POST request

### ISSUE THREAD

**Issue by anthonygore** [ethanresnick/json-api#119] opened 2016-08-07 22:18 UTC
Here's my model "session":

```
var sessionSchema = new mongoose.Schema({
    title: { type: String, required: true, unique: true },
    topic: { type: mongoose.Schema.ObjectId, ref: "Topic", required: true }
}, {collection: "liveSessions", timestamps: true });

module.exports = mongoose.model("Session", sessionSchema);
```

My request looks like this:

```
{
   "data":{
      "type":"sessions",
      "attributes":{
         "title":"Session title"
      },
      "relationships":{
         "topic":{
            "data":{
               "type":"topics",
               "id":"579c9337be84e820010dd5f0"
            }
         }
      }
   }
}
```

I always get back the error `Error: Path 'topic' is required.`

When I do some debugging I can see that initially json-api create a relationship resource. But when it goes to write it to the db, the relationship is now empty.

I can hack it and get it work by creating a beforeSave hook and doing this:

`resource._attrs.topic = resource._relationships.topic.linkage.value.id;`

Am I doing something wrong?

**Comment by ethanresnick** [comment] 2016-08-15 03:04
Hey. Sorry for the delayed response here. When you add `topic` to your mongoose schema, trying setting type to `mongoose.Schema.Types.ObjectId` instead of `mongoose.Schema.ObjectId`, and let me know if that fixes it!

**Comment by anthonygore** [comment] 2016-10-03 09:15
No it doesn't fix it :(

**Comment by ethanresnick** [comment] 2016-10-03 16:16
Hmm... that should work. Can you post a repo somewhere with the minimum code needed to reproduce the problem, and then I'll take a look?

**Comment by ethanresnick** [comment] 2017-06-25 03:39
Hi, I'm going to close this out, as I believe the problem is not with this library. If you're still having an issue, feel free to leave another comment.

**Closed by ethanresnick** 2017-06-25 03:39 UTC
